### ISSUE TITLE
limits the maximum number of fields allowed in a form

### ISSUE THREAD

**Issue by landsman** [pxson2903/prestashop-docker#1]
Thank you for this repository. You saved me such a lot time!
I found just one issue of php limits settings.

```
Warning! Your PHP configuration limits the maximum number of fields allowed in a form
1000 for max_input_vars.
Please ask your hosting provider to increase this limit to 1938 at least, or you will have to edit the translation files.
```

In case of manual module translation (https://www.leotheme.com/blog/prestashop/272-how-to-translate-prestashop-1-6-theme-and-modules.html)

![Screenshot from 2019-03-21 22-20-33](https://user-images.githubusercontent.com/3184228/54785850-8e849580-4c27-11e9-8973-7caa331e7d6a.png)

**Comment by pxson2903** [comment]
@landsman Thank you for your contribution. If you have any suggestions, feel free to ask me.

**Comment by landsman** [comment]
Thank you for merge :+1:
